package com.questlog.core.domain.model

object ClassAbilityDef {

    private val abilities: Map<CharacterClass, ClassAbility> = mapOf(
        CharacterClass.BARBARIAN to ClassAbility(
            key = "barbarian_rage",
            nameKo = "분노",
            nameEn = "Rage",
            description = "분노에 휩싸여 다음 전투에서 공격력이 폭발적으로 증가합니다.",
            flavorText = "\"피 맛이 나는군. 이제부터 본론이다.\"",
            resourceName = "분노",
            resourceMax = 2,
            cost = 1,
            buffEffect = BuffEffectType.ATTACK_BONUS,
            buffValue = 4,
            isImmediate = false,
        ),
        CharacterClass.BARD to ClassAbility(
            key = "bard_inspiration",
            nameKo = "영감 부여",
            nameEn = "Bardic Inspiration",
            description = "자신에게 음악적 영감을 불어넣어 다음 전투에서 획득 XP가 1.5배 증가합니다.",
            flavorText = "\"이 곡은 나를 위한 것. 전주가 끝나면 모든 것이 달라지리.\"",
            resourceName = "영감",
            resourceMax = 2,
            cost = 1,
            buffEffect = BuffEffectType.XP_MULTIPLIER,
            buffValue = 150,
            isImmediate = false,
        ),
        CharacterClass.CLERIC to ClassAbility(
            key = "cleric_cure_wounds",
            nameKo = "치유의 말씀",
            nameEn = "Cure Wounds",
            description = "신성한 에너지로 즉시 최대 HP의 25%를 회복합니다.",
            flavorText = "\"빛이여, 이 상처를 닫아라.\"",
            resourceName = "신성한 은총",
            resourceMax = 1,
            cost = 1,
            buffEffect = BuffEffectType.HP_RESTORE,
            buffValue = 25,
            isImmediate = true,
        ),
        CharacterClass.DRUID to ClassAbility(
            key = "druid_natural_resilience",
            nameKo = "자연의 보호",
            nameEn = "Natural Resilience",
            description = "자연의 힘으로 다음 전투에서 실패 시 받는 피해를 절반으로 줄입니다.",
            flavorText = "\"자연은 부러지지 않는다. 휘어질 뿐.\"",
            resourceName = "야생 형태",
            resourceMax = 2,
            cost = 1,
            buffEffect = BuffEffectType.DAMAGE_REDUCE,
            buffValue = 50,
            isImmediate = false,
        ),
        CharacterClass.FIGHTER to ClassAbility(
            key = "fighter_action_surge",
            nameKo = "행동 서지",
            nameEn = "Action Surge",
            description = "순간적으로 한계를 넘어 다음 전투에서 반드시 성공합니다.",
            flavorText = "\"훈련이 이 순간을 위한 것이었다.\"",
            resourceName = "행동 서지",
            resourceMax = 1,
            cost = 1,
            buffEffect = BuffEffectType.GUARANTEED_HIT,
            buffValue = 1,
            isImmediate = false,
        ),
        CharacterClass.MONK to ClassAbility(
            key = "monk_ki_strike",
            nameKo = "기 연타",
            nameEn = "Flurry of Blows",
            description = "기(氣)의 흐름에 집중해 다음 전투에서 공격 판정이 +3 상승합니다.",
            flavorText = "\"숨을 고르고. 흐름을 느끼고. 그리고 쳐라.\"",
            resourceName = "기 포인트",
            resourceMax = 2,
            cost = 1,
            buffEffect = BuffEffectType.ATTACK_BONUS,
            buffValue = 3,
            isImmediate = false,
        ),
        CharacterClass.PALADIN to ClassAbility(
            key = "paladin_divine_smite",
            nameKo = "신성 강타",
            nameEn = "Divine Smite",
            description = "신성한 빛을 무기에 담아 다음 전투에서 D20 ≥ 15를 크리티컬 히트로 처리합니다.",
            flavorText = "\"정의의 이름으로. 타올라라.\"",
            resourceName = "신성한 빛",
            resourceMax = 1,
            cost = 1,
            buffEffect = BuffEffectType.CRIT_THRESHOLD,
            buffValue = 15,
            isImmediate = false,
        ),
        CharacterClass.RANGER to ClassAbility(
            key = "ranger_favored_enemy",
            nameKo = "선호 적",
            nameEn = "Favored Enemy",
            description = "오랜 관찰로 대상의 약점을 파악해 다음 전투에서 XP 획득이 2배입니다.",
            flavorText = "\"나는 이 숲을 안다. 너의 발소리도 안다.\"",
            resourceName = "집중",
            resourceMax = 1,
            cost = 1,
            buffEffect = BuffEffectType.XP_MULTIPLIER,
            buffValue = 200,
            isImmediate = false,
        ),
        CharacterClass.ROGUE to ClassAbility(
            key = "rogue_sneak_attack",
            nameKo = "기습 공격",
            nameEn = "Sneak Attack",
            description = "적이 방심한 틈을 노려 다음 전투에서 공격 판정이 +5 상승합니다.",
            flavorText = "\"그들이 알아채기 전에 이미 끝이다.\"",
            resourceName = "기습 기회",
            resourceMax = 1,
            cost = 1,
            buffEffect = BuffEffectType.ATTACK_BONUS,
            buffValue = 5,
            isImmediate = false,
        ),
        CharacterClass.SORCERER to ClassAbility(
            key = "sorcerer_metamagic",
            nameKo = "변형 마법",
            nameEn = "Metamagic",
            description = "마법을 변형해 다음 전투에서 공격 판정이 +4 상승합니다.",
            flavorText = "\"주문은 내 피 속에 흐른다. 규칙 따위는 없다.\"",
            resourceName = "소서리 포인트",
            resourceMax = 2,
            cost = 1,
            buffEffect = BuffEffectType.ATTACK_BONUS,
            buffValue = 4,
            isImmediate = false,
        ),
        CharacterClass.WARLOCK to ClassAbility(
            key = "warlock_dark_luck",
            nameKo = "암흑의 계약",
            nameEn = "Dark One's Own Luck",
            description = "후원자와의 계약으로 다음 전투에서 반드시 성공합니다.",
            flavorText = "\"나는 실패를 계약서에서 삭제했다.\"",
            resourceName = "계약 충전",
            resourceMax = 1,
            cost = 1,
            buffEffect = BuffEffectType.GUARANTEED_HIT,
            buffValue = 1,
            isImmediate = false,
        ),
        CharacterClass.WIZARD to ClassAbility(
            key = "wizard_arcane_recovery",
            nameKo = "마법 회복",
            nameEn = "Arcane Recovery",
            description = "마법 에너지를 모아 즉시 HP를 완전히 회복합니다.",
            flavorText = "\"지식이 곧 치유다. 책을 읽어라.\"",
            resourceName = "비전 충전",
            resourceMax = 1,
            cost = 1,
            buffEffect = BuffEffectType.HP_RESTORE,
            buffValue = 100,
            isImmediate = true,
        ),
    )

    fun forClass(cls: CharacterClass): ClassAbility =
        abilities[cls] ?: abilities.getValue(CharacterClass.FIGHTER)
}
